# Generated by Django 4.2.30 on 2026-09-18 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID original del episodio en la API externa', unique=True)),
                ('name', models.CharField(help_text='Título del episodio', max_length=255)),
                ('air_date', models.CharField(help_text='Fecha de emisión original', max_length=255)),
                ('episode_code', models.CharField(help_text='Código de temporada y episodio (ej. S01E01)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en la base de datos local')),
            ],
        ),
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID original de la ubicación en la API externa', unique=True)),
                ('name', models.CharField(help_text='Nombre de la ubicación', max_length=255)),
                ('type', models.CharField(help_text='Tipo o categoría de la ubicación', max_length=255)),
                ('dimension', models.CharField(help_text='Dimensión a la que pertenece la ubicación', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en la base de datos local')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, help_text='ID original en la API', null=True, unique=True)),
                ('name', models.CharField(help_text='Nombre del personaje', max_length=255)),
                ('status', models.CharField(help_text='Estado vital del personaje', max_length=50)),
                ('species', models.CharField(help_text='Especie a la que pertenece', max_length=100)),
                ('gender', models.CharField(help_text='Género del personaje', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Enlace a la imagen oficial', max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro local')),
                ('episodes', models.ManyToManyField(help_text='Episodios en los que ha participado el personaje', related_name='characters', to='catalog.episode')),
                ('location', models.ForeignKey(blank=True, help_text='Ubicación asociada al personaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='catalog.ubication')),
            ],
        ),
    ]
